language: cpp
notifications:
  email: false
sudo: false
compiler:
  - gcc
os: linux
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./bin/test_code_generator
  - ./bin/test_bijective_checker --gtest-filter="BijectiveChecker.all_words_codes_mcmillan"
  