language: cpp

notifications:
  email: false

sudo: false

compiler:
  - gcc

os: linux

branches:
  only:
    - master
    - trivial_paths_tracking_edition

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./bin/code_generator_test
  - ./bin/bijective_checker_test

