language: cpp
notifications:
  email: false
sudo: false
compiler:
  - gcc
os: linux
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && make
#  - ./bin/code_generator_test
  - gdb -ex 'run' -ex 'backtrace' ./bin/bijective_checker_test
  